modLoader = "javafml"
loaderVersion = "[4,)"
license = "Unlicense"

[[mods]]
modId = "bertieblackholetest"
version = "1"
displayName = "Bertie Black Hole client tests"
description = "Test-only assertions for Bertie Black Hole"

[[dependencies.bertieblackholetest]]
modId = "bertie_blackhole"
type = "required"
versionRange = "[0.3,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.bertieblackholetest]]
modId = "forbidden_arcanus"
type = "required"
versionRange = "[2.6,)"
ordering = "AFTER"
side = "CLIENT"
